### ISSUE TITLE
Yorktown Chiller - Paul Koz  Purchase Checklist

### ISSUE THREAD

**Issue by JoeUlrich** [JoeUlrich/JoeU-test#12]
- [x] Eng- Identify Suppliers for project
- [ ] GP- Validate if suppliers in IBM Vendor List or Compro Vendor list
- [x] Eng- Budgetary Specs written by engineer and forwarded to procurement 
https://ibm.ent.box.com/folder/44595483119
Received by Joe Ulrich from Paul Kozlowski 12/15/17
- [x] GP- Budgetary Quote request reated and sent to ALL suppliers:
1/11/18 JU sent to all
- [ ] GP- Receive RFQs
- [ ] ALL- Review RFQs with Engineers
- [ ] ALL- Select Supplier
- [ ] GP- Equipment Agreement created/updated with Supplier
- [ ] GP-Source file needed (Over $500K?)
- [ ] ENG- Bond Cart created by requester
- [ ] ENG- Bond Cart Approved (MGR, Capital, WWCT approvals)
- [ ] GP- Equipment Agreement agreed/signed by IBM and Supplier?
- [ ] GP- Send Supplier PO
