### ISSUE TITLE
AFM - Atomic Force Microscope   (Mary Breton, John Gaudiello)

### ISSUE THREAD

**Issue by JoeUlrich** [JoeUlrich/JoeU-test#14]
Purchase of a AFM  for Albany Lab

- [x] Eng- Identify Suppliers for project
Park Systems. - Ardavan Zandiatashbar, Ph.D. Park Nanoscience Center
 3040 Olcott St., Santa Clara, CA 95054.  Tel: (518) 368-5060 | www.parkAFM.com
Bruker  https://www.bruker.com/products/surface-and-dimensional-analysis/atomic-force-microscopes.html
Bernie Woods.  Bernie.Wood@bruker.com 
Bruker Semiconductor Division
112 Robin Hill Road, Santa Barbara, CA 93117. Phone: 510-708-8117
- [x] 1.Eng - Identify all stakeholders in lab
- [ ] 2.GP- Validate if suppliers in IBM Vendor List or Compro Vendor list
- [ ] 3.GP - Reach out to suppliers for initial call
- [ ] 4.Eng - Set up meeting in Albany
- [ ] Eng- Specs written/approved by Engineers  (Appendix E)
- [ ] GP- Formal RFQ created and sent to ALL suppliers
- [ ] GP- Receive RFQs
- [ ] ALL- Review RFQs with Engineers
- [ ] ALL- Select Supplier
- [ ] GP- Equipment Agreement created/updated with Supplier
- [ ] GP-Source file needed (Over $500K?)
- [ ] ENG- Bond Cart created by requester
- [ ] ENG- Bond Cart Approved (MGR, Capital, WWCT approvals)
- [ ] GP- Equipment Agreement agreed/signed by IBM and Supplier?
- [ ] GP- Send Supplier PO
