### ISSUE TITLE
AFM Project procurement checklist

### ISSUE THREAD

**Issue by JoeUlrich** [JoeUlrich/JoeU-test#15]
- [x] Eng- Identify Suppliers for project
        Park Systems
        Bruker  https://www.bruker.com/products/surface-and-dimensional-analysis/atomic-force-microscopes.html
- [x] Eng - Identify all stakeholders in lab
- [ ] GP- Validate if suppliers in IBM Vendor List or Compro Vendor list
- [ ] GP - Reach out to suppliers for initial call
- [ ] Eng - Set up meeting in Albany
- [ ] Eng- Specs written/approved by Engineers  (Appendix E)
- [ ] GP- Formal RFQ created and sent to ALL suppliers
- [ ] GP- Receive RFQs
- [ ] ALL- Review RFQs with Engineers
- [ ] ALL- Select Supplier
- [ ] GP- Equipment Agreement created/updated with Supplier
- [ ] GP-Source file needed (Over $500K?)
- [ ] ENG- Bond Cart created by requester
- [ ] ENG- Bond Cart Approved (MGR, Capital, WWCT approvals)
- [ ] GP- Equipment Agreement agreed/signed by IBM and Supplier?
- [ ] GP- Send Supplier PO
