### ISSUE TITLE
EVG Yorktown Purchase

### ISSUE THREAD

**Issue by JoeUlrich** [JoeUlrich/JoeU-test#4]
EPIC Creation for EVG
- [x] Eng- Identify Suppliers for project
- [x] GP- Validate if suppliers in IBM Vendor List or Compro Vendor list
- [x] Eng- Specs written/approved by Engineers  (Appendix E)
             Paul Kozlowski specs -->> https://ibm.ent.box.com/folder/42459348801
- [x] GP- Formal RFQ created and sent to ALL suppliers
             EVG Quote -->  https://ibm.ent.box.com/file/251157385212
             Mark Systems Quote -->>  https://ibm.ent.box.com/file/250600098452
- [x] GP- Receive RFQs
- [x] ALL- Review RFQs with Engineers
- [x] ALL- Select Supplier
- [ ] GP- Equipment Agreement created/updated with Supplier
- [x] GP-Source file needed (Over $500K?)
- [x] ENG- Bond Cart created by requester
- [x] ENG- Bond Cart Approved (MGR, Capital, WWCT approvals)
- [ ] GP- Equipment Agreement agreed/signed by IBM and Supplier?
- [ ] GP- Send Supplier PO

**Comment by JoeUlrich** [comment]
f
